[DEFAULT]
auth_strategy = keystone
transport_url = {{ .TransportURL }}

[keystone_authtoken]
www_authenticate_uri={{ .KeystonePublicURL }}
auth_url={{ .KeystoneInternalURL }}
auth_type={{ if .UseApplicationCredentials }}v3applicationcredential{{ else }}password{{ end }}
{{ if .UseApplicationCredentials -}}
application_credential_id = {{ .ACID }}
application_credential_secret = {{ .ACSecret }}
{{- else -}}
project_domain_name=Default
user_domain_name=Default
project_name=service
username={{ .ServiceUser }}
password = {{ .ServicePassword }}
{{- end }}

[service_catalog]
auth_url={{ .KeystoneInternalURL }}
auth_type={{ if .UseApplicationCredentials }}v3applicationcredential{{ else }}password{{ end }}
{{ if .UseApplicationCredentials -}}
application_credential_id = {{ .ACID }}
application_credential_secret = {{ .ACSecret }}
{{- else -}}
username={{ .ServiceUser }}
password = {{ .ServicePassword }}
user_domain_name=Default
project_name=service
project_domain_name=Default
{{- end }}

[ironic]
auth_url={{ .KeystoneInternalURL }}
auth_type={{ if .UseApplicationCredentials }}v3applicationcredential{{ else }}password{{ end }}
{{ if .UseApplicationCredentials -}}
application_credential_id = {{ .ACID }}
application_credential_secret = {{ .ACSecret }}
{{- else -}}
username={{ .ServiceUser }}
password = {{ .ServicePassword }}
user_domain_name=Default
project_name=service
project_domain_name=Default
{{- end }}

[agent]
report_interval=30

{{ if (index . "QuorumQueues") }}
[oslo_messaging_rabbit]
rabbit_quorum_queue=true
rabbit_transient_quorum_queue=true
amqp_durable_queues=true
{{ end }}
