[DEFAULT]
enabled_console_interfaces={{if .GraphicalConsolesEnabled}}redfish-graphical,fake-graphical,{{end}}ipmitool-socat,no-console,fake

[conductor]
heartbeat_interval=20
heartbeat_timeout=120
allow_provisioning_in_maintenance=false
{{ if .ConductorGroup }}conductor_group={{ .ConductorGroup }}{{ end }}
# TODO: uncomment the below entry when we move to ironic release 2025.2 or later
#{{- if .GracefulShutdownTimeout }}
# graceful_shutdown_timeout={{ .GracefulShutdownTimeout }}
#{{- end }}

{{if .GraphicalConsolesEnabled}}
[vnc]
enabled=True
container_provider=kubernetes
console_image={{ .ConsoleImage }}
read_only=false
kubernetes_container_template=/etc/ironic/ironic-console-pod.yaml.template
{{end}}
