#!/bin/env python3
#
# Copyright 2023 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import os
import json
import sys

# Uses network status from pod:
#   metadata.annotations['k8s.v1.cni.cncf.io/networks-status']
#
# Example network status json string:
#
# [
#   { "name": "openshift-sdn",
#     "interface": "eth0",
#     "ips": [ "10.131.0.76" ],
#     "default": true, "dns": {}
#   },
#   { "name": "openstack/baremetal-net",
#     "interface": "net1",
#     "ips": [ "192.168.24.1" ],
#     "mac": "5e:ff:15:d9:66:84",
#     "dns": {}
#   }
# ]
#

def get_ip_from_network_status():
    namespace = os.environ.get('PodNamespace')
    net_status = json.loads(os.environ.get('PodNetworksStatus'))
    net_attachment_name = sys.argv[1]

    for net in net_status:
        if net.get('name') == '/'.join([namespace, net_attachment_name]):
            ips = net.get('ips', [])
            if len(ips) > 0:
                print(ips[0])
                return
            raise Exception(
                f"Network {net_attachment_name} does not have any "
                "IP address.")

    raise Exception(
        f"Network {net_attachment_name} not in pod network_status: "
        f"{net_status}")

if __name__ == '__main__':
    get_ip_from_network_status()
